### ISSUE TITLE
[Berlin] - Workflow use-case for Table Session

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/SeQuenC-UseCases#12]
## Problem Statement

Table Session on Dec 3rd should have a workflow use-case for presentation.

## Expected Behavior

The workflow should incorporate a FOKUS use-case and can be presented at the table session.

## Tasks

- [ ] Choose Use-case in colaboration with FOKUS
- [ ] Create a workflow interacting with qunicorn
- [ ] Test the use-case

## Notes

Could potentially be a jupyter notebook locally executing python scripts, then fetching results from camunda
