### ISSUE TITLE
Create demo für FOKUS workshop

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/SeQuenC-UseCases#5]
## Problem Statement

FOKUS Workshop for integration of PlanQK components and use-cases

## Expected Behavior

Prepared sequenc-platform with demo walktrhoughs and the usage of different components.

## Tasks

- [ ] Prepare the docker-compose with all the components
  - [ ] Fix the docker images for the workshop
- [ ] Convert it to a functional kubenetes and test it with minikube
- [ ] Test the kubenetes in the IONOS cluster
  - [ ] Document the steps and guidelines for the deployment to IONOS
  - [ ] Write a tutorial for deploying all the components
  - [ ] Test the deployed components via simple use-cases
- [ ] Write HELM-charts for the components
  - [ ] Place the HELM-charts in the respective Repository in the SeQuenC-Consortium
  - [ ] Document the usage of the HELM-charts
- [ ] Prepare demo show cases for
  - [ ] QC-Atlas with the Qunicorn integration
  - [ ] Workflow-Modeler interacting with qunicorn
  - [ ] OpenTOSCA & Winery to deploy a component (maybe circuit generator)
  - [ ] Workflow Engine explanation
  - [ ] Qunicorn Tutorial
  - [ ] Show different Qunicorn features
- [ ] Document and create a README.md similar to QuantME use-cases

## Notes

Priority is on the integration tasks!!
