### ISSUE TITLE
Refactor QC-Atlas

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/SeQuenC-UseCases#6]
## Problem Statement

QC-Atlas' execution component is implemented as god-component.

## Expected Behavior

Refactor the implementation to meet the best-practises in Angular.

## Tasks

- [ ] Divide functionality in different components
- [ ] Test, that the functionality is still intact
- [ ] Enhance the visuals
- [ ]  _Replace the mat-tab with better implementation_
