### ISSUE TITLE
Bloqcat - Use-case

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/SeQuenC-UseCases#7]
## Problem Statement

Show a use-case of the bloqcat framwork with the sequenc components

## References (Optional)

Use-case should be structured similar to Use-cases in this Repo: https://github.com/UST-QuAntiL/QuantME-UseCases 

## Expected Behavior

Provide a step-by-step guide to startup and use all components.

## Tasks

- [x] Build the docker-compose with all necessary components
- [x] Test the use-case (Deutsch's Algorithm)
- [x] Write the readme with all necessary information and pictures
- [x] Provide all the necessary files in this repo

## Notes
